[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flexgang-case-management"
version = "0.1.0"
description = "Backend API for Case Management system to help clients find employment"
authors = [ {name = "Team flexgang"} ]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "fastapi>=0.103.2",
    "uvicorn>=0.23.2",
    "sqlalchemy>=2.0.21",
    "alembic>=1.12.0",
    "pydantic>=2.4.2",
    "python-jose>=3.3.0",
    "passlib>=1.7.4",
    "bcrypt>=4.0.1",
    "python-multipart>=0.0.6",
    "python-dotenv>=1.0.0",
    "psycopg2-binary>=2.9.9",
    "pandas>=2.0.0",
    "scikit-learn>=1.4.2",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.2.0",
    "black>=23.10.0",
    "pylint>=3.0.1",
    "isort>=5.12.1",
]

[tool.black]
line-length = 88
target-version = ["py38"]

[tool.isort]
profile = "black"
line_length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[tool.setuptools]
package-dir = {"" = "app"}
